
// Mutações de Tasks
export const SET_TASKS = "TASK/SET";

export const SET_PROJECT = "PROJECT/SET"
export const SET_PROJECT_DETAIL = "PROJECT/SET_DETAIL"
export const SET_PROJECT_COLLABORATES = "PROJECT/SET_COLLABORATE"